AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: <<ProjectName>> service
Resources:
  ApiHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <<ProjectName>>-bundle.zip
      Handler: <<ProjectName>>.handlers.handler
      Runtime: python3.6
      Events:
        ApiName:
          Type: Api
          Properties:
            Path: /hello
            Method: any
